name: synapse-sdk
on:
  push:
    branches:
      - master
    paths:
      - "packages/synapse-sdk/**"
      - .github/workflows/synapse-sdk.yml
  pull_request:
    paths:
      - "packages/synapse-sdk/**"
      - .github/workflows/synapse-sdk.yml
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        node: [lts/*, current]
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node }}
      - name: Playwright for Windows
        if: matrix.os == 'windows-latest'
        run: pnpx playwright install winldd
      - name: Install Dependencies
        run: pnpm install
      - name: Run tests
        run: |
          pnpm config set script-shell bash
          pnpm -r --filter @filoz/synapse-sdk run test
      - name: Check docs build
        run: pnpm -r --filter docs run build
  # docs:
  #   name: Docs
  #   concurrency:
  #     group: pages
  #     cancel-in-progress: false
  #   permissions:
  #     contents: read
  #     pages: write
  #     id-token: write
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/master'
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   steps:
  #     - uses: actions/checkout@v5
  #     - uses: actions/setup-node@v5
  #       with:
  #         node-version: lts/*
  #     - run: npm install --no-progress --no-package-lock --no-save
  #     - run: npm run lint
  #     - run: cd docs && npm install && npm run build
  #     - uses: actions/configure-pages@v5
  #     - uses: actions/upload-pages-artifact@v4
  #       with:
  #         path: ./docs/dist
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4
